### PR TITLE
Change naming scheme of wip branches

### PR DESCRIPTION
**Pull request by gregoralbrecht**
imo the naming scheme for wip branches should be better readable and sortable and thus prefixed not postfixed.

### CODE REVIEW

**Comment by coderbyheart** [comment]
-1 because I like to have the WIP branches grouped next to the feature branch, they belong to.

**Comment by gregoralbrecht** [comment]
I'm beginning to understand how you guys defined a wip. So if wip branches are sub-feature branches for each person working on a feature and if wip and feature are directly related, I will close this PR.

Imo this wasn't really clear from the previous PR.
In my mind, a wip is something people can work on - maybe for a longer time frame - that can't be attributed to a specific feature, release date, whatever.

**Comment by gregoralbrecht** [comment]
I'm beginning to understand how you guys defined wip. So if wip branches 
are
sub-feature branches for each person working on a feature and they are 
directly
related I will close this PR.

Imo this wasn't really clear from the previous PR.

**Comment by coderbyheart** [comment]
The key info is: `git stash` that is stored remotely.

**Pull request closed without merging**
